#----------------------Library Declarations--------------------------####

library(tidyverse)
library(ggpubr)
library(rstatix)
library(lme4)
library(arm)
library(lattice)
library(effects)
library(sjPlot)
library(piecewiseSEM)
library(glmmTMB)
library(lmtest)
library(emmeans)

# Download a package if it's not installed yet
if (!require(package, character.only=T, quietly=T)) {
  install.packages(package)
  library(package, character.only = T)
}
#---------------------------------------------------------------------###
#----------------------Parameters------------------------------------####

# alter the directory and the datafile name here
directory = 'C:/Users/rondin/Desktop/Courses/Computational Psycholinguistics/Assignment/Assignment 2'
filename = 'datafile_p2.csv'

#---------------------------------------------------------------------###
#----------------------Data Prep-------------------------------------####

setwd(directory)
data <- read.csv(file = filename)

# double-check data format
tail(data)

# mark categorical variables
data$word = as.factor(data$word)
data$word_pos = as.factor(data$word_pos)
data$ambiguity = as.factor(data$ambiguity)
data$fit = as.factor(data$fit)
data$model = as.factor(data$model)
#---------------------------------------------------------------------###
#----------------------Model Implementation--------------------------####

# Question 1: what predictions regarding the effects of ambiguity and 
# thematic fit on reading?

# then fit a model with surprisal generated by LSTM alone
data.lstm <- data[which(data$model=="lstm"),]
#tail(data.lstm)
lme.lstm <- lmerTest::lmer(surprisal ~ ambiguity + fit # main effects
                           + ambiguity:fit # interaction
                           + (1 | word) + (1 | word_pos), # random structure
                           data = data.lstm)
summary(lme.lstm)
# multiple comparisons
emm.lstm = emmeans(lme.lstm, ~ ambiguity*fit)
pairs(emm.lstm)

# Question 2: will SRN do just as well as LSTM?

# first fit a model for SRN surprisal only (for plotting)
data.srn <- data[which(data$model=="srn"),]
#tail(data.lstm)
lme.srn <- lmerTest::lmer(surprisal ~ ambiguity + fit # main effects
                           + ambiguity:fit # interaction
                           + (1 | word) + (1 | word_pos), # random structure
                           data = data.srn)
summary(lme.srn)
# multiple comparisons
emm.srn = emmeans(lme.srn, ~ ambiguity*fit)
pairs(emm.srn)

# fit a model for comparing two RNN model outputs
lme.full <- lmerTest::lmer(surprisal ~ ambiguity + fit + model # main effects
                          + ambiguity:fit
                          + ambiguity:model
                          + fit:model
                          + ambiguity:fit:model# interaction
                          + (1 | word) + (1 | word_pos), # random structure
                          data = data)
summary(lme.full)
# multiple comparisons
emm = emmeans(lme.full, ~ model*fit)
pairs(emm)
#-------------------------------Plotting-----------------------------------####
# plotting interactions
amb_fit_lstm = plot_model(lme.lstm,type ='eff',terms = c('ambiguity','fit'), legend.title = "fit") +
  ylim(9, 12.5)
amb_fit_srn = plot_model(lme.srn,type ='eff',terms = c('ambiguity','fit'), legend.title = "fit") +
  ylim(9, 12.5)

# comparison model
model = plot_model(lme.full,type ='eff',terms = c('model'))
model_fit = plot_model(lme.full,type ='eff',terms = c('model','fit'), legend.title = "fit")
